apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}

      containers:
        - name: log-writer
          image: olekacak/log-output:2.1
          imagePullPolicy: Always
          command: ["php", "artisan", "log:output"]
          volumeMounts:
            - name: shared-logs
              mountPath: /shared

        - name: log-reader
          image: olekacak/log-output:2.1
          imagePullPolicy: Always
          command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-logs
              mountPath: /shared