apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt

      containers:
        - name: log-writer
          image: olekacak/log-output:2.6
          imagePullPolicy: Always
          command: ["php", "artisan", "log:output"]
          volumeMounts:
            - name: shared-logs
              mountPath: /shared

        - name: log-reader
          image: olekacak/log-output:2.6
          imagePullPolicy: Always
          command: ["sh", "-c", "php -S 0.0.0.0:8000 -t public"]
          ports:
            - containerPort: 8000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
            - name: config-volume
              mountPath: /config