apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      volumes:
        - name: todo-pv
          persistentVolumeClaim:
            claimName: todo-pvc

      containers:
        - name: todo-app
          image: olekacak/todo-app:2.6
          imagePullPolicy: Always
          command: ["sh", "-c", "php -S 0.0.0.0:8000 -t public"]

          env:
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: TODO_BACKEND_URL

          ports:
            - containerPort: 8000

          volumeMounts:
            - name: todo-pv
              mountPath: /shared